version: '3.8'

networks:
  local-net:
    external: true

services:
  zg_generator:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: zg_generator
    # ports:
    #   - "8888:8888"
    #   - "50051:50051"
    env_file:
      - .env-docker
    networks:
      - local-net  
    volumes:
      - ./zg_generator:/app
    restart: unless-stopped
