version: '3.8'

networks:
  local-net:
    external: true

services:
  zg_generator:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: zg_generator
    env_file:
      - .env-docker
    networks:
      - local-net
    ports:
      - "21122:21122"
    volumes:
      - ./zg_generator:/app
    restart: unless-stopped
