version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zg_generator
    ports:
      - "8888:8888"
      - "50051:50051"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
